/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef distrust_CONSTANTS_H
#define distrust_CONSTANTS_H

#include "distrust_types.h"

namespace distrust {

class distrustConstants {
 public:
  distrustConstants();

};

extern const distrustConstants g_distrust_constants;

} // namespace

#endif
