/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "distrust_constants.h"

namespace distrust {

const distrustConstants g_distrust_constants;

distrustConstants::distrustConstants() {
}

} // namespace

